### ISSUE TITLE
Support for -h, --help or help is missing up to now

### ISSUE THREAD

**Issue by guettli** [jnrbsn/daemonocle#28]
```
python d.py --help

Traceback (most recent call last):
  File "d.py", line 16, in <module>
    daemon.do_action(sys.argv[1])
  File "/home/guettli/projects/lala-env/lib/python3.8/site-packages/daemonocle/core.py", line 887, in do_action
    func = self.get_action(action)
  File "/home/guettli/projects/lala-env/lib/python3.8/site-packages/daemonocle/core.py", line 883, in get_action
    return get_action(self, action)
  File "/home/guettli/projects/lala-env/lib/python3.8/site-packages/daemonocle/core.py", line 56, in get_action
    raise DaemonError(
daemonocle.exceptions.DaemonError: Invalid action "--help"
```

I think `-h`, `--help` and `help` should be supported by the library.

**Comment by jnrbsn** [comment]
Use the click integration described in the README. It has a `--help` option built-in.
